bbtools_dedup_wc:                    '{fs_prefix}/{df}/reads/{preproc}__bbtdedup_{params}/{df_sample}_R1.fastq.gz'
fastq_gz_bbtools_dedup_R1_wc:        '{fs_prefix}/{df}/reads/{preproc}__bbtdedup_{params}/{df_sample}_R1.fastq.gz'
fastq_gz_bbtools_dedup_R2_wc:        '{fs_prefix}/{df}/reads/{preproc}__bbtdedup_{params}/{df_sample}_R2.fastq.gz'
fastq_gz_bbtools_dedup_log_wc:       '{fs_prefix}/{df}/reads/{preproc}__bbtdedup_{params}/{df_sample}.log'