multiqc_strand_file_set_dir_wc: '{fs_prefix}/{df}/profile/multiqc/{sample_set}/'
multiqc_sample_set_dir_wc: '{fs_prefix}/{df}/profile/multiqc/{sample_set}/'
multiqc_wc :        '{fs_prefix}/{df}/profile/multiqc/{sample_set}/multiqc_report_{strand}.html'