bbtools_tadpole_wc:                    '{fs_prefix}/{df}/reads/{preproc}__bbtdpl_{params}/{fs_name}_R1.fastq.gz'
fastq_gz_bbtools_tadpole_R1_wc:        '{fs_prefix}/{df}/reads/{preproc}__bbtdpl_{params}/{fs_name}_R1.fastq.gz'
fastq_gz_bbtools_tadpole_R2_wc:        '{fs_prefix}/{df}/reads/{preproc}__bbtdpl_{params}/{fs_name}_R2.fastq.gz'
fastq_gz_bbtools_tadpole_log_wc:       '{fs_prefix}/{df}/reads/{preproc}__bbtdpl_{params}/{fs_name}.log'