fastqc_wc: '{fs_prefix}/{df}/profile/fastqc/{preproc}/{df_sample}/{df_sample}_{strand}_fastqc.zip'

fastq_gz_file_wc: '{fs_prefix}/{df}/reads/{preproc}/{df_sample}_{strand}.fastq.gz'
fastq_gz_R1_wc: '{fs_prefix}/{df}/reads/{preproc}/{df_sample}_R1.fastq.gz'
fastq_gz_R2_wc: '{fs_prefix}/{df}/reads/{preproc}/{df_sample}_R2.fastq.gz'
md5_fastq_gz:     '{fs_prefix}/{df}/reads/{preproc}/{df_sample}/profile/{df_sample}_{strand}.md5'

fastqc_data_wc:   '{fs_prefix}/{df}/profile/fastqc/{preproc}/{df_sample}/{df_sample}_{strand}_fastqc/fastqc_data.txt'
fastqc_zip_wc: '{fs_prefix}/{df}/profile/fastqc/{preproc}/{df_sample}/{df_sample}_{strand}_fastqc.zip'
